//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Sad.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string TypeMaterial { get; set; }
        public string Provider { get; set; }
        public string AmountPackage { get; set; }
        public string EdIzm { get; set; }
        public string QuantityStock { get; set; }
        public string MinQuantity { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string MaterialImage { get; set; }
        public Nullable<int> HistoryRemainderID { get; set; }
        public Nullable<int> ProductionID { get; set; }
    
        public virtual HistoryRemainder HistoryRemainder { get; set; }
        public virtual Production Production { get; set; }
    }
}
