//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren2_Sad.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Agent = new HashSet<Agent>();
            this.Production = new HashSet<Production>();
            this.ProductSale = new HashSet<ProductSale>();
            this.TypeProduct1 = new HashSet<TypeProduct>();
        }
    
        public int ID { get; set; }
        public string Vendor { get; set; }
        public string Name { get; set; }
        public string TypeProduct { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string MinPrice { get; set; }
        public string Sertificate { get; set; }
        public string NumberStandart { get; set; }
        public string SizePackage { get; set; }
        public string PackingWeight { get; set; }
        public string UnpackedWeight { get; set; }
        public string NumberWorkshop { get; set; }
        public string NumberOfPeople { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent> Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeProduct> TypeProduct1 { get; set; }
    }
}
